Repository KajananGit/Bright-Tasks, pull requests merged in 2024-08, with the labels that each got.

#10 Setup prettier, husky and lint-staged.
  bright-tasks-frontend/.husky/pre-commit
  bright-tasks-frontend/package-lock.json
  bright-tasks-frontend/package.json
Labels: enhancement

#15 Install prop-types. Format and lint code.
  bright-tasks-frontend/eslint.config.js
  bright-tasks-frontend/package-lock.json
  bright-tasks-frontend/package.json
  bright-tasks-frontend/src/App.jsx
  bright-tasks-frontend/src/components/Login.jsx
  bright-tasks-frontend/src/components/SignUp.jsx
  bright-tasks-frontend/src/containers/LoginContainer.jsx
  bright-tasks-frontend/src/containers/SignUpContainer.jsx
  bright-tasks-frontend/src/index.css
  bright-tasks-frontend/src/main.jsx
  bright-tasks-frontend/vite.config.js
Labels: bug

#17 Create README.md
  README.md
Labels: documentation

#20 Feature/color scheme
  Get-It-Done-Wireframe.excalidraw
  UML-ERD.excalidraw
  bright-tasks-frontend/src/index.css
Labels: documentation, enhancement

#16 Added the basics of the navbar component
  bright-tasks-frontend/package-lock.json
  bright-tasks-frontend/package.json
  bright-tasks-frontend/src/App.css
  bright-tasks-frontend/src/App.jsx
  bright-tasks-frontend/src/components/Navigation.jsx
  bright-tasks-frontend/src/containers/LoginContainer.jsx
  bright-tasks-frontend/src/containers/SignUpContainer.jsx
  bright-tasks-frontend/src/styling/NavigationStyle.css
Labels: enhancement
